In [1]:
import numpy as np

In [3]:
a=np.array([3,4,5,6])

In [4]:
type(a)

numpy.ndarray

In [5]:
a1= np.array([[3,4,5,],[5,6,7]])

In [6]:
a1

array([[3, 4, 5],
       [5, 6, 7]])

In [7]:
a1.shape

(2, 3)

In [8]:
a1.ndim

2

In [9]:
a1.size

6

In [12]:
np.random.randint(1,10,(3,3))

array([[7, 2, 7],
       [6, 7, 4],
       [9, 8, 3]], dtype=int32)

In [16]:
np.random.randint(2,5,(2,3,3))

array([[[4, 4, 3],
        [3, 4, 3],
        [4, 4, 4]],

       [[3, 3, 4],
        [4, 3, 3],
        [3, 2, 4]]], dtype=int32)